### ISSUE TITLE
Cant find all intersections

### ISSUE THREAD

**Issue by DigitCell** [kirill-terekhov/SweepLine#2]
work fast but you can see on picture that not all cases find
![image](https://user-images.githubusercontent.com/66899439/181599986-5f78cada-1ec5-4a4d-a9d5-5c7507d4e6c5.png)

**Comment by DigitCell** [comment]
one more change in code char to uint as unique index of point

**Comment by kirill-terekhov** [comment]
Please provide a test case

**Comment by DigitCell** [comment]
Think better to check your code yourself or make remark that is some bugs.
Sorry, but have no time to write exporter data from project,
take another open code and all works well.

**Comment by kirill-terekhov** [comment]
I don't use it

**Comment by weiwen1990** [comment]
I have found one test case: a polygon with 6 vertices and 6 edges accordingly.
vertices in order:
{ -1338.702453, -2505.548004 },
{ -1335.757360, -2520.439809 },
{ -1337.920564, -2519.336472 },
{ -1337.349319, -2519.363378 },
{ -1336.389307, -2519.435794 },
{ -1335.399262, -2519.574411 },
There should be 1 intersection between edge[p0, p1] and edge[p4, p5] but the output is zero.
Thanks.
